export default {
  common: { save: 'সংরক্ষণ', cancel: 'বাতিল', delete: 'মুছুন', edit: 'সম্পাদনা', add: 'যোগ করুন', done: 'সম্পন্ন', next: 'পরবর্তী', back: 'পেছনে', skip: 'এড়িয়ে যান', loading: 'লোড হচ্ছে...', error: 'কিছু ভুল হয়েছে', retry: 'আবার চেষ্টা করুন', yes: 'হ্যাঁ', no: 'না', ok: 'ঠিক আছে', share: 'শেয়ার করুন', export: 'রপ্তানি করুন', minutes: 'মিনিট', hours: 'ঘণ্টা', kg: 'কেজি', cm: 'সেমি', ml: 'মিলি' },
  auth: { welcome: 'BabySaathi-তে আপনাকে স্বাগতম', tagline: 'আপনার শিশুকে বোঝে এমন AI সঙ্গী', getStarted: 'শুরু করুন', login: 'লগইন', register: 'অ্যাকাউন্ট তৈরি করুন', email: 'ইমেইল', password: 'পাসওয়ার্ড', confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন', phone: 'ফোন নম্বর', name: 'পুরো নাম', otpSent: '{{phone}}-এ OTP পাঠানো হয়েছে', enterOtp: 'OTP লিখুন', resendOtp: 'OTP পুনরায় পাঠান', loginWithGoogle: 'Google দিয়ে চালিয়ে যান', loginWithApple: 'Apple দিয়ে চালিয়ে যান', loginWithPhone: 'ফোন দিয়ে চালিয়ে যান', loginWithEmail: 'ইমেইল দিয়ে চালিয়ে যান', forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?', noAccount: 'অ্যাকাউন্ট নেই?', haveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?', signUp: 'সাইন আপ', signIn: 'সাইন ইন', resetPassword: 'পাসওয়ার্ড রিসেট করুন', resetPasswordSent: 'পাসওয়ার্ড রিসেট ইমেইল পাঠানো হয়েছে', termsAgreement: 'চালিয়ে যাওয়ার মাধ্যমে আপনি আমাদের সেবার শর্তাবলী সম্মত হচ্ছেন' },
  tabs: { home: 'হোম', tracker: 'ট্র্যাকার', ai: 'AI', journal: 'জার্নাল', profile: 'প্রোফাইল' },
  home: { goodMorning: 'শুভ সকাল', goodAfternoon: 'শুভ দুপুর', goodEvening: 'শুভ সন্ধ্যা', todaySummary: 'আজকের সারসংক্ষেপ', feeds: 'খাওয়ানো', sleep: 'ঘুম', diapers: 'ডায়াপার', cries: 'কান্না', aiInsight: 'AI অন্তর্দৃষ্টি', nextVaccine: 'পরবর্তী টিকা', due: 'বাকি', quickLog: 'দ্রুত লগ', noInsights: 'এখনও কোনো অন্তর্দৃষ্টি নেই। ট্র্যাক করতে থাকুন!' },
  ai: { title: 'AI সহকারী', cryDetector: 'কান্না সনাক্তকারী', listening: 'শুনছে...', analyzing: 'বিশ্লেষণ করছে...', startListening: 'শোনা শুরু করুন', stopListening: 'শোনা বন্ধ করুন', cryResult: 'কান্না বিশ্লেষণ', hunger: 'ক্ষুধা', sleep: 'ঘুমন্ত', discomfort: 'অস্বস্তি', pain: 'ব্যথা', unknown: 'অজানা', wasCorrrrect: 'এটি কি সঠিক ছিল?', yes: 'হ্যাঁ, সঠিক!', no: 'না, এটি ছিল...', chatPlaceholder: 'আপনার শিশু সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...', suggestedQuestions: ['শিশু কেন কাঁদছে?', 'স্বাভাবিক ঘুম কতটুকু?', 'পরবর্তী টিকা কখন?', 'এই বৃদ্ধি কি স্বাভাবিক?'], digitalTwin: 'ডিজিটাল টুইন', twinAccuracy: 'ভবিষ্যদ্বাণীর নির্ভুলতা', insightsTitle: 'AI অন্তর্দৃষ্টি' },
  tracker: { title: 'ট্র্যাকার', feeding: 'খাওয়ানো', sleep: 'ঘুম', diaper: 'ডায়াপার', growth: 'বৃদ্ধি', vaccination: 'টিকাদান', milestone: 'মাইলস্টোন', breastfeed: 'বুকের দুধ', formula: 'ফর্মুলা', solid: 'শক্ত খাবার', leftSide: 'বাম', rightSide: 'ডান', both: 'উভয়', startFeeding: 'খাওয়ানো শুরু', stopFeeding: 'খাওয়ানো বন্ধ', feedDuration: 'সময়কাল', amount: 'পরিমাণ (মিলি)', brand: 'ব্র্যান্ড', foodType: 'খাবারের ধরন', startSleep: 'শিশু ঘুমিয়েছে', stopSleep: 'শিশু জেগেছে', sleepDuration: 'ঘুমের সময়কাল', sleepQuality: 'ঘুমের মান', good: 'ভালো', fair: 'মোটামুটি', poor: 'খারাপ', wet: 'ভেজা', dirty: 'নোংরা', mixed: 'মিশ্র', logDiaper: 'ডায়াপার লগ', weight: 'ওজন', height: 'উচ্চতা', headCirc: 'মাথার পরিধি', logGrowth: 'বৃদ্ধি লগ', growthChart: 'বৃদ্ধি চার্ট', upcoming: 'আসন্ন', overdue: 'বিলম্বিত', administered: 'দেওয়া হয়েছে', markDone: 'সম্পন্ন চিহ্নিত করুন', vaccineDate: 'টিকার তারিখ', achieved: 'অর্জিত', pending: 'বাকি', markAchieved: 'অর্জিত চিহ্নিত করুন', categories: { physical: 'শারীরিক', social: 'সামাজিক', language: 'ভাষা', cognitive: 'জ্ঞানীয়' } },
  journal: { title: 'মেমোরি জার্নাল', addEntry: 'স্মৃতি যোগ করুন', photos: 'ফটো', videos: 'ভিডিও', notes: 'নোট', tags: 'ট্যাগ', mood: { happy: 'খুশি', neutral: 'স্বাভাবিক', tired: 'ক্লান্ত', worried: 'চিন্তিত' }, monthlyRecap: 'মাসিক সারসংক্ষেপ', memoryBook: 'মেমোরি বুক', noEntries: 'এখনও কোনো স্মৃতি নেই।' },
  profile: { title: 'প্রোফাইল', editProfile: 'প্রোফাইল সম্পাদনা', babies: 'আমার শিশু', addBaby: 'শিশু যোগ করুন', family: 'পরিবার শেয়ারিং', inviteFamily: 'পরিবারকে আমন্ত্রণ জানান', subscription: 'সদস্যপদ', upgradePremium: 'প্রিমিয়ামে আপগ্রেড করুন', doctorReport: 'ডাক্তার রিপোর্ট তৈরি করুন', settings: 'সেটিংস', language: 'ভাষা', notifications: 'বিজ্ঞপ্তি', darkMode: 'ডার্ক মোড', privacyPolicy: 'গোপনীয়তা নীতি', termsOfService: 'সেবার শর্তাবলী', helpSupport: 'সাহায্য', logout: 'লগআউট', version: 'সংস্করণ {{version}}' },
  onboarding: { addBaby: 'আপনার শিশু যোগ করুন', babyName: 'শিশুর নাম', birthDate: 'জন্ম তারিখ', gender: 'লিঙ্গ', male: 'ছেলে', female: 'মেয়ে', other: 'অন্যান্য', birthWeight: 'জন্মের সময় ওজন (কেজি)', birthHeight: 'জন্মের সময় উচ্চতা (সেমি)', enableNotifications: 'বিজ্ঞপ্তি সক্ষম করুন', notificationsDesc: 'খাওয়ানো, ঘুম এবং টিকাদানের জন্য রিমাইন্ডার পান', enableMicrophone: 'মাইক্রোফোন সক্ষম করুন', microphoneDesc: 'AI কান্না সনাক্তকরণের জন্য প্রয়োজন', enableCamera: 'ক্যামেরা সক্ষম করুন', cameraDesc: 'মূল্যবান মুহূর্তগুলি ধারণ করুন', allSet: 'সব প্রস্তুত!', allSetDesc: 'BabySaathi আপনার এবং আপনার শিশুর সাহায্যের জন্য প্রস্তুত', allowAccess: 'অনুমতি দিন', maybeLayer: 'পরে' },
  errors: { network: 'নেটওয়ার্ক ত্রুটি।', auth: 'প্রমাণীকরণ ব্যর্থ।', permission: 'অনুমতি অস্বীকৃত।', unknown: 'একটি অপ্রত্যাশিত ত্রুটি ঘটেছে।' },
  subscription: { free: 'বিনামূল্যে', premium: 'প্রিমিয়াম', premiumFamily: 'প্রিমিয়াম ফ্যামিলি', perMonth: '/মাস', perYear: '/বছর', upgradeNow: 'এখন আপগ্রেড করুন', features: { free: ['বেসিক ট্র্যাকিং', 'বেসিক কান্না সনাক্তকরণ', '৩০ দিনের ইতিহাস'], premium: ['AI অন্তর্দৃষ্টি', 'ভবিষ্যদ্বাণী', 'সীমাহীন ইতিহাস', 'ডাক্তার রিপোর্ট', 'পরিবার শেয়ারিং'], premiumFamily: ['একাধিক শিশু', 'সীমাহীন পরিচর্যাকারী', 'উন্নত AI', 'অগ্রাধিকার সমর্থন'] } },
};
