export default {
  common: { save: 'जतन करा', cancel: 'रद्द करा', delete: 'हटवा', edit: 'संपादित करा', add: 'जोडा', done: 'झाले', next: 'पुढे', back: 'मागे', skip: 'वगळा', loading: 'लोड होत आहे...', error: 'काहीतरी चुकले', retry: 'पुन्हा प्रयत्न करा', yes: 'होय', no: 'नाही', ok: 'ठीक', share: 'शेअर करा', export: 'निर्यात करा', minutes: 'मिनिटे', hours: 'तास', kg: 'किलो', cm: 'सेमी', ml: 'मिली' },
  auth: { welcome: 'BabySaathi मध्ये आपले स्वागत आहे', tagline: 'तुमच्या बाळाला समजणारा AI साथीदार', getStarted: 'सुरू करा', login: 'लॉगिन', register: 'खाते तयार करा', email: 'ईमेल', password: 'पासवर्ड', confirmPassword: 'पासवर्ड पुष्टी करा', phone: 'फोन नंबर', name: 'पूर्ण नाव', otpSent: '{{phone}} वर OTP पाठवला', enterOtp: 'OTP टाका', resendOtp: 'OTP पुन्हा पाठवा', loginWithGoogle: 'Google सोबत सुरू ठेवा', loginWithApple: 'Apple सोबत सुरू ठेवा', loginWithPhone: 'फोनसोबत सुरू ठेवा', loginWithEmail: 'ईमेलसोबत सुरू ठेवा', forgotPassword: 'पासवर्ड विसरलात?', noAccount: 'खाते नाही?', haveAccount: 'आधीच खाते आहे?', signUp: 'साइन अप करा', signIn: 'साइन इन करा', resetPassword: 'पासवर्ड रीसेट करा', resetPasswordSent: 'पासवर्ड रीसेट ईमेल पाठवला', termsAgreement: 'सुरू ठेवून आपण आमच्या अटींशी सहमत आहात' },
  tabs: { home: 'मुख्यपृष्ठ', tracker: 'ट्रॅकर', ai: 'AI', journal: 'जर्नल', profile: 'प्रोफाइल' },
  home: { goodMorning: 'शुभ प्रभात', goodAfternoon: 'शुभ दुपार', goodEvening: 'शुभ संध्याकाळ', todaySummary: 'आजचा सारांश', feeds: 'आहार', sleep: 'झोप', diapers: 'डायपर', cries: 'रडणे', aiInsight: 'AI माहिती', nextVaccine: 'पुढील लस', due: 'बाकी', quickLog: 'जलद लॉग', noInsights: 'अजून कोणतीही माहिती नाही. ट्रॅक करत राहा!' },
  ai: { title: 'AI सहाय्यक', cryDetector: 'रडणे शोधक', listening: 'ऐकत आहे...', analyzing: 'विश्लेषण करत आहे...', startListening: 'ऐकणे सुरू करा', stopListening: 'ऐकणे थांबवा', cryResult: 'रडणे विश्लेषण', hunger: 'भूक', sleep: 'झोप', discomfort: 'अस्वस्थता', pain: 'वेदना', unknown: 'अज्ञात', wasCorrrrect: 'हे बरोबर होते का?', yes: 'होय, बरोबर!', no: 'नाही, ते होते...', chatPlaceholder: 'तुमच्या बाळाबद्दल काहीही विचारा...', suggestedQuestions: ['बाळ का रडत आहे?', 'सामान्य झोप किती आहे?', 'पुढील लस कधी आहे?', 'हा विकास सामान्य आहे का?'], digitalTwin: 'डिजिटल ट्विन', twinAccuracy: 'अंदाज अचूकता', insightsTitle: 'AI माहिती' },
  tracker: { title: 'ट्रॅकर', feeding: 'आहार', sleep: 'झोप', diaper: 'डायपर', growth: 'वाढ', vaccination: 'लसीकरण', milestone: 'मैलाचा दगड', breastfeed: 'स्तनपान', formula: 'फॉर्म्युला', solid: 'घन अन्न', leftSide: 'डावी बाजू', rightSide: 'उजवी बाजू', both: 'दोन्ही', startFeeding: 'आहार सुरू करा', stopFeeding: 'आहार थांबवा', feedDuration: 'कालावधी', amount: 'प्रमाण (मिली)', brand: 'ब्रँड', foodType: 'अन्नाचा प्रकार', startSleep: 'बाळ झोपले', stopSleep: 'बाळ जागे झाले', sleepDuration: 'झोपेचा कालावधी', sleepQuality: 'झोपेची गुणवत्ता', good: 'चांगली', fair: 'ठीक', poor: 'वाईट', wet: 'ओले', dirty: 'घाण', mixed: 'मिश्रित', logDiaper: 'डायपर लॉग', weight: 'वजन', height: 'उंची', headCirc: 'डोक्याचा घेर', logGrowth: 'वाढ लॉग', growthChart: 'वाढ आलेख', upcoming: 'येणारे', overdue: 'उशीर', administered: 'दिले', markDone: 'पूर्ण म्हणून चिन्हांकित करा', vaccineDate: 'लसीचा दिनांक', achieved: 'साध्य केले', pending: 'बाकी', markAchieved: 'साध्य म्हणून चिन्हांकित करा', categories: { physical: 'शारीरिक', social: 'सामाजिक', language: 'भाषा', cognitive: 'संज्ञानात्मक' } },
  journal: { title: 'मेमरी जर्नल', addEntry: 'आठवण जोडा', photos: 'फोटो', videos: 'व्हिडिओ', notes: 'नोट्स', tags: 'टॅग', mood: { happy: 'आनंदी', neutral: 'सामान्य', tired: 'थकलेले', worried: 'काळजीत' }, monthlyRecap: 'मासिक सारांश', memoryBook: 'मेमरी बुक', noEntries: 'अजून आठवणी नाहीत.' },
  profile: { title: 'प्रोफाइल', editProfile: 'प्रोफाइल संपादित करा', babies: 'माझी मुले', addBaby: 'मूल जोडा', family: 'कुटुंब सामायिकरण', inviteFamily: 'कुटुंबातील सदस्याला आमंत्रित करा', subscription: 'सदस्यता', upgradePremium: 'प्रीमियमवर अपग्रेड करा', doctorReport: 'डॉक्टर अहवाल तयार करा', settings: 'सेटिंग्ज', language: 'भाषा', notifications: 'सूचना', darkMode: 'डार्क मोड', privacyPolicy: 'गोपनीयता धोरण', termsOfService: 'सेवा अटी', helpSupport: 'मदत', logout: 'लॉगआउट', version: 'आवृत्ती {{version}}' },
  onboarding: { addBaby: 'तुमचे बाळ जोडा', babyName: 'बाळाचे नाव', birthDate: 'जन्म तारीख', gender: 'लिंग', male: 'मुलगा', female: 'मुलगी', other: 'इतर', birthWeight: 'जन्माचे वजन (किलो)', birthHeight: 'जन्माची उंची (सेमी)', enableNotifications: 'सूचना सक्षम करा', notificationsDesc: 'आहार, झोप आणि लसीकरणासाठी रिमाइंडर', enableMicrophone: 'मायक्रोफोन सक्षम करा', microphoneDesc: 'AI रडणे शोधासाठी आवश्यक', enableCamera: 'कॅमेरा सक्षम करा', cameraDesc: 'अमूल्य क्षण टिपा', allSet: 'सर्व तयार!', allSetDesc: 'BabySaathi तुम्हाला आणि तुमच्या बाळाला मदत करण्यासाठी तयार आहे', allowAccess: 'परवानगी द्या', maybeLayer: 'नंतर' },
  errors: { network: 'नेटवर्क त्रुटी.', auth: 'प्रमाणीकरण अयशस्वी.', permission: 'परवानगी नाकारली.', unknown: 'अनपेक्षित त्रुटी.' },
  subscription: { free: 'विनामूल्य', premium: 'प्रीमियम', premiumFamily: 'प्रीमियम फॅमिली', perMonth: '/महिना', perYear: '/वर्ष', upgradeNow: 'आता अपग्रेड करा', features: { free: ['मूलभूत ट्रॅकिंग', 'मूलभूत रडणे शोध', '30 दिवसांचा इतिहास'], premium: ['AI माहिती', 'अंदाज', 'अमर्यादित इतिहास', 'डॉक्टर अहवाल', 'कुटुंब सामायिकरण'], premiumFamily: ['एकाधिक मुले', 'अमर्यादित काळजीवाहक', 'प्रगत AI', 'प्राधान्य समर्थन'] } },
};
