export default {
  common: { save: 'ਸੁਰੱਖਿਅਤ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', delete: 'ਮਿਟਾਓ', edit: 'ਸੰਪਾਦਿਤ ਕਰੋ', add: 'ਜੋੜੋ', done: 'ਹੋ ਗਿਆ', next: 'ਅਗਲਾ', back: 'ਵਾਪਸ', skip: 'ਛੱਡੋ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', error: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ', retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ', yes: 'ਹਾਂ', no: 'ਨਹੀਂ', ok: 'ਠੀਕ ਹੈ', share: 'ਸਾਂਝਾ ਕਰੋ', export: 'ਨਿਰਯਾਤ ਕਰੋ', minutes: 'ਮਿੰਟ', hours: 'ਘੰਟੇ', kg: 'ਕਿਲੋ', cm: 'ਸੈਮੀ', ml: 'ਮਿਲੀ' },
  auth: { welcome: 'BabySaathi ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ', tagline: 'ਤੁਹਾਡੇ ਬੱਚੇ ਨੂੰ ਸਮਝਣ ਵਾਲਾ AI ਸਾਥੀ', getStarted: 'ਸ਼ੁਰੂ ਕਰੋ', login: 'ਲੌਗਿਨ', register: 'ਖਾਤਾ ਬਣਾਓ', email: 'ਈਮੇਲ', password: 'ਪਾਸਵਰਡ', confirmPassword: 'ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ ਕਰੋ', phone: 'ਫ਼ੋਨ ਨੰਬਰ', name: 'ਪੂਰਾ ਨਾਮ', otpSent: '{{phone}} ਤੇ OTP ਭੇਜਿਆ', enterOtp: 'OTP ਦਰਜ ਕਰੋ', resendOtp: 'OTP ਦੁਬਾਰਾ ਭੇਜੋ', loginWithGoogle: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ', loginWithApple: 'Apple ਨਾਲ ਜਾਰੀ ਰੱਖੋ', loginWithPhone: 'ਫ਼ੋਨ ਨਾਲ ਜਾਰੀ ਰੱਖੋ', loginWithEmail: 'ਈਮੇਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ', forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?', noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?', haveAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?', signUp: 'ਸਾਈਨ ਅੱਪ', signIn: 'ਸਾਈਨ ਇਨ', resetPassword: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ', resetPasswordSent: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਈਮੇਲ ਭੇਜੀ', termsAgreement: 'ਜਾਰੀ ਰੱਖ ਕੇ ਤੁਸੀਂ ਸਾਡੀਆਂ ਸ਼ਰਤਾਂ ਨਾਲ ਸਹਿਮਤ ਹੋ' },
  tabs: { home: 'ਹੋਮ', tracker: 'ਟਰੈਕਰ', ai: 'AI', journal: 'ਜਰਨਲ', profile: 'ਪ੍ਰੋਫਾਈਲ' },
  home: { goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ', goodAfternoon: 'ਸ਼ੁਭ ਦੁਪਹਿਰ', goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ', todaySummary: 'ਅੱਜ ਦਾ ਸਾਰ', feeds: 'ਦੁੱਧ ਪਿਲਾਉਣਾ', sleep: 'ਨੀਂਦ', diapers: 'ਡਾਇਪਰ', cries: 'ਰੋਣਾ', aiInsight: 'AI ਜਾਣਕਾਰੀ', nextVaccine: 'ਅਗਲਾ ਟੀਕਾ', due: 'ਬਾਕੀ', quickLog: 'ਜਲਦੀ ਲੌਗ', noInsights: 'ਅਜੇ ਕੋਈ ਜਾਣਕਾਰੀ ਨਹੀਂ। ਟਰੈਕ ਕਰਦੇ ਰਹੋ!' },
  ai: { title: 'AI ਸਹਾਇਕ', cryDetector: 'ਰੋਣਾ ਡਿਟੈਕਟਰ', listening: 'ਸੁਣ ਰਿਹਾ ਹੈ...', analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...', startListening: 'ਸੁਣਨਾ ਸ਼ੁਰੂ ਕਰੋ', stopListening: 'ਸੁਣਨਾ ਬੰਦ ਕਰੋ', cryResult: 'ਰੋਣਾ ਵਿਸ਼ਲੇਸ਼ਣ', hunger: 'ਭੁੱਖ', sleep: 'ਨੀਂਦ', discomfort: 'ਤਕਲੀਫ਼', pain: 'ਦਰਦ', unknown: 'ਅਣਜਾਣ', wasCorrrrect: 'ਕੀ ਇਹ ਸਹੀ ਸੀ?', yes: 'ਹਾਂ, ਸਹੀ!', no: 'ਨਹੀਂ, ਇਹ ਸੀ...', chatPlaceholder: 'ਆਪਣੇ ਬੱਚੇ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ...', suggestedQuestions: ['ਬੱਚਾ ਕਿਉਂ ਰੋ ਰਿਹਾ ਹੈ?', 'ਸਾਧਾਰਨ ਨੀਂਦ ਕਿੰਨੀ ਹੈ?', 'ਅਗਲਾ ਟੀਕਾ ਕਦੋਂ ਹੈ?', 'ਕੀ ਇਹ ਵਿਕਾਸ ਸਾਧਾਰਨ ਹੈ?'], digitalTwin: 'ਡਿਜੀਟਲ ਟਵਿਨ', twinAccuracy: 'ਭਵਿੱਖਬਾਣੀ ਸ਼ੁੱਧਤਾ', insightsTitle: 'AI ਜਾਣਕਾਰੀਆਂ' },
  tracker: { title: 'ਟਰੈਕਰ', feeding: 'ਦੁੱਧ ਪਿਲਾਉਣਾ', sleep: 'ਨੀਂਦ', diaper: 'ਡਾਇਪਰ', growth: 'ਵਿਕਾਸ', vaccination: 'ਟੀਕਾਕਰਨ', milestone: 'ਮੀਲਪੱਥਰ', breastfeed: 'ਛਾਤੀ ਦਾ ਦੁੱਧ', formula: 'ਫਾਰਮੂਲਾ', solid: 'ਠੋਸ ਖੁਰਾਕ', leftSide: 'ਖੱਬੇ', rightSide: 'ਸੱਜੇ', both: 'ਦੋਵੇਂ', startFeeding: 'ਦੁੱਧ ਪਿਲਾਉਣਾ ਸ਼ੁਰੂ', stopFeeding: 'ਦੁੱਧ ਪਿਲਾਉਣਾ ਬੰਦ', feedDuration: 'ਸਮਾਂ', amount: 'ਮਾਤਰਾ (ਮਿਲੀ)', brand: 'ਬ੍ਰਾਂਡ', foodType: 'ਖੁਰਾਕ ਦੀ ਕਿਸਮ', startSleep: 'ਬੱਚਾ ਸੁੱਤਾ', stopSleep: 'ਬੱਚਾ ਜਾਗਿਆ', sleepDuration: 'ਨੀਂਦ ਦਾ ਸਮਾਂ', sleepQuality: 'ਨੀਂਦ ਦੀ ਗੁਣਵੱਤਾ', good: 'ਚੰਗੀ', fair: 'ਠੀਕ', poor: 'ਮਾੜੀ', wet: 'ਗਿੱਲਾ', dirty: 'ਗੰਦਾ', mixed: 'ਮਿਲਿਆ', logDiaper: 'ਡਾਇਪਰ ਲੌਗ', weight: 'ਭਾਰ', height: 'ਕੱਦ', headCirc: 'ਸਿਰ ਦਾ ਘੇਰਾ', logGrowth: 'ਵਿਕਾਸ ਲੌਗ', growthChart: 'ਵਿਕਾਸ ਚਾਰਟ', upcoming: 'ਆਉਣ ਵਾਲਾ', overdue: 'ਦੇਰੀ', administered: 'ਦਿੱਤਾ ਗਿਆ', markDone: 'ਪੂਰਾ ਮਾਰਕ ਕਰੋ', vaccineDate: 'ਟੀਕੇ ਦੀ ਤਾਰੀਖ', achieved: 'ਪ੍ਰਾਪਤ', pending: 'ਬਾਕੀ', markAchieved: 'ਪ੍ਰਾਪਤ ਮਾਰਕ ਕਰੋ', categories: { physical: 'ਸਰੀਰਕ', social: 'ਸਮਾਜਿਕ', language: 'ਭਾਸ਼ਾ', cognitive: 'ਬੌਧਿਕ' } },
  journal: { title: 'ਮੈਮੋਰੀ ਜਰਨਲ', addEntry: 'ਯਾਦ ਜੋੜੋ', photos: 'ਫੋਟੋ', videos: 'ਵੀਡੀਓ', notes: 'ਨੋਟਸ', tags: 'ਟੈਗ', mood: { happy: 'ਖੁਸ਼', neutral: 'ਸਾਧਾਰਨ', tired: 'ਥੱਕਿਆ', worried: 'ਚਿੰਤਤ' }, monthlyRecap: 'ਮਾਸਿਕ ਸਾਰ', memoryBook: 'ਮੈਮੋਰੀ ਬੁੱਕ', noEntries: 'ਅਜੇ ਕੋਈ ਯਾਦਾਂ ਨਹੀਂ।' },
  profile: { title: 'ਪ੍ਰੋਫਾਈਲ', editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ', babies: 'ਮੇਰੇ ਬੱਚੇ', addBaby: 'ਬੱਚਾ ਜੋੜੋ', family: 'ਪਰਿਵਾਰ ਸਾਂਝਾਕਰਨ', inviteFamily: 'ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨੂੰ ਸੱਦਾ', subscription: 'ਸਦੱਸਤਾ', upgradePremium: 'ਪ੍ਰੀਮੀਅਮ ਵਿੱਚ ਅੱਪਗ੍ਰੇਡ', doctorReport: 'ਡਾਕਟਰ ਰਿਪੋਰਟ ਬਣਾਓ', settings: 'ਸੈਟਿੰਗਾਂ', language: 'ਭਾਸ਼ਾ', notifications: 'ਸੂਚਨਾਵਾਂ', darkMode: 'ਡਾਰਕ ਮੋਡ', privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ', termsOfService: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ', helpSupport: 'ਮਦਦ', logout: 'ਲੌਗਆਊਟ', version: 'ਸੰਸਕਰਣ {{version}}' },
  onboarding: { addBaby: 'ਆਪਣਾ ਬੱਚਾ ਜੋੜੋ', babyName: 'ਬੱਚੇ ਦਾ ਨਾਮ', birthDate: 'ਜਨਮ ਤਾਰੀਖ', gender: 'ਲਿੰਗ', male: 'ਮੁੰਡਾ', female: 'ਕੁੜੀ', other: 'ਹੋਰ', birthWeight: 'ਜਨਮ ਭਾਰ (ਕਿਲੋ)', birthHeight: 'ਜਨਮ ਕੱਦ (ਸੈਮੀ)', enableNotifications: 'ਸੂਚਨਾਵਾਂ ਚਾਲੂ ਕਰੋ', notificationsDesc: 'ਦੁੱਧ, ਨੀਂਦ ਅਤੇ ਟੀਕੇ ਲਈ ਰਿਮਾਈਂਡਰ', enableMicrophone: 'ਮਾਈਕ੍ਰੋਫੋਨ ਚਾਲੂ ਕਰੋ', microphoneDesc: 'AI ਰੋਣਾ ਖੋਜ ਲਈ ਜ਼ਰੂਰੀ', enableCamera: 'ਕੈਮਰਾ ਚਾਲੂ ਕਰੋ', cameraDesc: 'ਕੀਮਤੀ ਪਲ ਕੈਦ ਕਰੋ', allSet: 'ਸਭ ਤਿਆਰ!', allSetDesc: 'BabySaathi ਤੁਹਾਡੀ ਅਤੇ ਤੁਹਾਡੇ ਬੱਚੇ ਦੀ ਮਦਦ ਲਈ ਤਿਆਰ ਹੈ', allowAccess: 'ਇਜਾਜ਼ਤ ਦਿਓ', maybeLayer: 'ਬਾਅਦ ਵਿੱਚ' },
  errors: { network: 'ਨੈੱਟਵਰਕ ਗੜਬੜ।', auth: 'ਪ੍ਰਮਾਣੀਕਰਨ ਅਸਫਲ।', permission: 'ਇਜਾਜ਼ਤ ਤੋਂ ਇਨਕਾਰ।', unknown: 'ਅਣਕਿਆਸੀ ਗੜਬੜ।' },
  subscription: { free: 'ਮੁਫ਼ਤ', premium: 'ਪ੍ਰੀਮੀਅਮ', premiumFamily: 'ਪ੍ਰੀਮੀਅਮ ਫੈਮਿਲੀ', perMonth: '/ਮਹੀਨਾ', perYear: '/ਸਾਲ', upgradeNow: 'ਹੁਣੇ ਅੱਪਗ੍ਰੇਡ ਕਰੋ', features: { free: ['ਬੇਸਿਕ ਟਰੈਕਿੰਗ', 'ਬੇਸਿਕ ਰੋਣਾ ਖੋਜ', '30 ਦਿਨਾਂ ਦਾ ਇਤਿਹਾਸ'], premium: ['AI ਜਾਣਕਾਰੀ', 'ਭਵਿੱਖਬਾਣੀਆਂ', 'ਅਸੀਮਿਤ ਇਤਿਹਾਸ', 'ਡਾਕਟਰ ਰਿਪੋਰਟਾਂ', 'ਪਰਿਵਾਰ ਸਾਂਝਾਕਰਨ'], premiumFamily: ['ਕਈ ਬੱਚੇ', 'ਅਸੀਮਿਤ ਦੇਖਭਾਲਕਰਤਾ', 'ਉੱਨਤ AI', 'ਤਰਜੀਹੀ ਸਹਾਇਤਾ'] } },
};
