export default {
  common: { save: 'சேமி', cancel: 'ரத்து', delete: 'நீக்கு', edit: 'திருத்து', add: 'சேர்', done: 'முடிந்தது', next: 'அடுத்து', back: 'பின்', skip: 'தவிர்', loading: 'ஏற்றுகிறது...', error: 'பிழை ஏற்பட்டது', retry: 'மீண்டும் முயற்சி', yes: 'ஆம்', no: 'இல்லை', ok: 'சரி', share: 'பகிர்', export: 'ஏற்றுமதி', minutes: 'நிமிடம்', hours: 'மணி', kg: 'கிலோ', cm: 'செமீ', ml: 'மிலி' },
  auth: { welcome: 'BabySaathi-க்கு வரவேற்கிறோம்', tagline: 'உங்கள் குழந்தையை புரிந்துகொள்ளும் AI துணை', getStarted: 'தொடங்கு', login: 'உள்நுழை', register: 'கணக்கு உருவாக்கு', email: 'மின்னஞ்சல்', password: 'கடவுச்சொல்', confirmPassword: 'கடவுச்சொல் உறுதிசெய்', phone: 'தொலைபேசி எண்', name: 'முழு பெயர்', otpSent: '{{phone}}-க்கு OTP அனுப்பப்பட்டது', enterOtp: 'OTP உள்ளிடு', resendOtp: 'OTP மீண்டும் அனுப்பு', loginWithGoogle: 'Google மூலம் தொடர்', loginWithApple: 'Apple மூலம் தொடர்', loginWithPhone: 'தொலைபேசி மூலம் தொடர்', loginWithEmail: 'மின்னஞ்சல் மூலம் தொடர்', forgotPassword: 'கடவுச்சொல் மறந்தீர்களா?', noAccount: 'கணக்கு இல்லையா?', haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?', signUp: 'பதிவு செய்', signIn: 'உள்நுழை', resetPassword: 'கடவுச்சொல் மீட்டமை', resetPasswordSent: 'கடவுச்சொல் மீட்டமை மின்னஞ்சல் அனுப்பப்பட்டது', termsAgreement: 'தொடர்வதன் மூலம் நீங்கள் எங்கள் விதிமுறைகளை ஒப்புக்கொள்கிறீர்கள்' },
  tabs: { home: 'முகப்பு', tracker: 'கண்காணிப்பு', ai: 'AI', journal: 'நினைவேடு', profile: 'சுயவிவரம்' },
  home: { goodMorning: 'காலை வணக்கம்', goodAfternoon: 'மதிய வணக்கம்', goodEvening: 'மாலை வணக்கம்', todaySummary: 'இன்றைய சுருக்கம்', feeds: 'உணவூட்டல்', sleep: 'தூக்கம்', diapers: 'டையப்பர்', cries: 'அழுகை', aiInsight: 'AI நுண்ணறிவு', nextVaccine: 'அடுத்த தடுப்பூசி', due: 'நிலுவை', quickLog: 'விரைவு பதிவு', noInsights: 'இன்னும் நுண்ணறிவு இல்லை. தொடர்ந்து கண்காணிக்கவும்!' },
  ai: { title: 'AI உதவியாளர்', cryDetector: 'அழுகை கண்டறிவி', listening: 'கேட்கிறது...', analyzing: 'பகுப்பாய்கிறது...', startListening: 'கேட்கத் தொடங்கு', stopListening: 'கேட்பதை நிறுத்து', cryResult: 'அழுகை பகுப்பாய்வு', hunger: 'பசி', sleep: 'தூக்கம்', discomfort: 'அசௌகர்யம்', pain: 'வலி', unknown: 'தெரியாத', wasCorrrrect: 'இது சரியாக இருந்ததா?', yes: 'ஆம், சரி!', no: 'இல்லை, இது...', chatPlaceholder: 'உங்கள் குழந்தையைப் பற்றி எதையும் கேளுங்கள்...', suggestedQuestions: ['குழந்தை ஏன் அழுகிறது?', 'சாதாரண தூக்கம் எவ்வளவு?', 'அடுத்த தடுப்பூசி எப்போது?', 'இந்த வளர்ச்சி சாதாரணமா?'], digitalTwin: 'டிஜிட்டல் இரட்டையர்', twinAccuracy: 'கணிப்பு துல்லியம்', insightsTitle: 'AI நுண்ணறிவு' },
  tracker: { title: 'கண்காணிப்பு', feeding: 'உணவூட்டல்', sleep: 'தூக்கம்', diaper: 'டையப்பர்', growth: 'வளர்ச்சி', vaccination: 'தடுப்பூசி', milestone: 'மைல்கல்', breastfeed: 'தாய்ப்பால்', formula: 'ஃபார்முலா', solid: 'திட உணவு', leftSide: 'இடது', rightSide: 'வலது', both: 'இரண்டும்', startFeeding: 'உணவூட்டல் தொடங்கு', stopFeeding: 'உணவூட்டல் நிறுத்து', feedDuration: 'கால அளவு', amount: 'அளவு (மிலி)', brand: 'பிராண்ட்', foodType: 'உணவு வகை', startSleep: 'குழந்தை தூங்கியது', stopSleep: 'குழந்தை எழுந்தது', sleepDuration: 'தூக்க கால அளவு', sleepQuality: 'தூக்க தரம்', good: 'நல்ல', fair: 'சரியான', poor: 'மோசமான', wet: 'ஈரமான', dirty: 'அழுக்கான', mixed: 'கலந்த', logDiaper: 'டையப்பர் பதிவு', weight: 'எடை', height: 'உயரம்', headCirc: 'தலை சுற்றளவு', logGrowth: 'வளர்ச்சி பதிவு', growthChart: 'வளர்ச்சி விளக்கப்படம்', upcoming: 'வரவிருக்கும்', overdue: 'தாமதமான', administered: 'கொடுக்கப்பட்டது', markDone: 'முடிந்தது என குறி', vaccineDate: 'தடுப்பூசி தேதி', achieved: 'அடைந்தது', pending: 'நிலுவை', markAchieved: 'அடைந்தது என குறி', categories: { physical: 'உடல்', social: 'சமூக', language: 'மொழி', cognitive: 'அறிவாற்றல்' } },
  journal: { title: 'நினைவு நினைவேடு', addEntry: 'நினைவு சேர்', photos: 'புகைப்படங்கள்', videos: 'வீடியோக்கள்', notes: 'குறிப்புகள்', tags: 'குறிச்சொற்கள்', mood: { happy: 'மகிழ்ச்சி', neutral: 'சாதாரண', tired: 'சோர்வு', worried: 'கவலை' }, monthlyRecap: 'மாதாந்திர சுருக்கம்', memoryBook: 'நினைவு புத்தகம்', noEntries: 'இன்னும் நினைவுகள் இல்லை.' },
  profile: { title: 'சுயவிவரம்', editProfile: 'சுயவிவரம் திருத்து', babies: 'என் குழந்தைகள்', addBaby: 'குழந்தை சேர்', family: 'குடும்ப பகிர்வு', inviteFamily: 'குடும்பத்தினரை அழை', subscription: 'சந்தா', upgradePremium: 'பிரீமியமாக மேம்படுத்து', doctorReport: 'மருத்துவர் அறிக்கை உருவாக்கு', settings: 'அமைப்புகள்', language: 'மொழி', notifications: 'அறிவிப்புகள்', darkMode: 'இருண்ட பயன்முறை', privacyPolicy: 'தனியுரிமை கொள்கை', termsOfService: 'சேவை விதிமுறைகள்', helpSupport: 'உதவி', logout: 'வெளியேறு', version: 'பதிப்பு {{version}}' },
  onboarding: { addBaby: 'உங்கள் குழந்தையை சேர்க்கவும்', babyName: 'குழந்தையின் பெயர்', birthDate: 'பிறந்த தேதி', gender: 'பாலினம்', male: 'ஆண்', female: 'பெண்', other: 'மற்றவை', birthWeight: 'பிறப்பு எடை (கிலோ)', birthHeight: 'பிறப்பு உயரம் (செமீ)', enableNotifications: 'அறிவிப்புகளை இயக்கு', notificationsDesc: 'உணவூட்டல், தூக்கம் மற்றும் தடுப்பூசிக்கான நினைவூட்டல்கள்', enableMicrophone: 'மைக்ரோஃபோனை இயக்கு', microphoneDesc: 'AI அழுகை கண்டறிதலுக்கு தேவை', enableCamera: 'கேமராவை இயக்கு', cameraDesc: 'விலைமதிப்பற்ற தருணங்களை பதிவு செய்', allSet: 'எல்லாம் தயார்!', allSetDesc: 'BabySaathi உங்களுக்கும் உங்கள் குழந்தைக்கும் உதவ தயாராக உள்ளது', allowAccess: 'அனுமதி வழங்கு', maybeLayer: 'பிறகு' },
  errors: { network: 'நெட்வொர்க் பிழை.', auth: 'அங்கீகாரம் தோல்வியடைந்தது.', permission: 'அனுமதி மறுக்கப்பட்டது.', unknown: 'எதிர்பாராத பிழை.' },
  subscription: { free: 'இலவசம்', premium: 'பிரீமியம்', premiumFamily: 'பிரீமியம் குடும்பம்', perMonth: '/மாதம்', perYear: '/ஆண்டு', upgradeNow: 'இப்போது மேம்படுத்து', features: { free: ['அடிப்படை கண்காணிப்பு', 'அடிப்படை அழுகை கண்டறிதல்', '30 நாள் வரலாறு'], premium: ['AI நுண்ணறிவு', 'கணிப்புகள்', 'வரம்பற்ற வரலாறு', 'மருத்துவர் அறிக்கை', 'குடும்ப பகிர்வு'], premiumFamily: ['பல குழந்தைகள்', 'வரம்பற்ற பராமரிப்பாளர்கள்', 'மேம்பட்ட AI', 'முன்னுரிமை ஆதரவு'] } },
};
