export default {
  common: { save: 'సేవ్', cancel: 'రద్దు', delete: 'తొలగించు', edit: 'సవరించు', add: 'జోడించు', done: 'పూర్తైంది', next: 'తదుపరి', back: 'వెనుకకు', skip: 'దాటు', loading: 'లోడ్ అవుతోంది...', error: 'లోపం సంభవించింది', retry: 'మళ్ళీ ప్రయత్నించు', yes: 'అవును', no: 'కాదు', ok: 'సరే', share: 'పంచుకో', export: 'ఎగుమతి', minutes: 'నిమిషాలు', hours: 'గంటలు', kg: 'కిలో', cm: 'సెమీ', ml: 'మిలీ' },
  auth: { welcome: 'BabySaathi కి స్వాగతం', tagline: 'మీ బిడ్డను అర్థం చేసుకునే AI తోడు', getStarted: 'ప్రారంభించు', login: 'లాగిన్', register: 'ఖాతా తయారు చేయి', email: 'ఇమెయిల్', password: 'పాస్‌వర్డ్', confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించు', phone: 'ఫోన్ నంబర్', name: 'పూర్తి పేరు', otpSent: '{{phone}} కు OTP పంపబడింది', enterOtp: 'OTP నమోదు చేయి', resendOtp: 'OTP మళ్ళీ పంపు', loginWithGoogle: 'Google తో కొనసాగు', loginWithApple: 'Apple తో కొనసాగు', loginWithPhone: 'ఫోన్ తో కొనసాగు', loginWithEmail: 'ఇమెయిల్ తో కొనసాగు', forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?', noAccount: 'ఖాతా లేదా?', haveAccount: 'ఇప్పటికే ఖాతా ఉందా?', signUp: 'సైన్ అప్', signIn: 'సైన్ ఇన్', resetPassword: 'పాస్‌వర్డ్ రీసెట్', resetPasswordSent: 'పాస్‌వర్డ్ రీసెట్ ఇమెయిల్ పంపబడింది', termsAgreement: 'కొనసాగించడం ద్వారా మీరు మా నిబంధనలకు అంగీకరిస్తున్నారు' },
  tabs: { home: 'హోమ్', tracker: 'ట్రాకర్', ai: 'AI', journal: 'జర్నల్', profile: 'ప్రొఫైల్' },
  home: { goodMorning: 'శుభోదయం', goodAfternoon: 'శుభ మధ్యాహ్నం', goodEvening: 'శుభ సాయంత్రం', todaySummary: 'నేటి సారాంశం', feeds: 'తినిపించడం', sleep: 'నిద్ర', diapers: 'డైపర్', cries: 'ఏడుపు', aiInsight: 'AI అంతర్దృష్టి', nextVaccine: 'తదుపరి టీకా', due: 'బకాయి', quickLog: 'శీఘ్ర లాగ్', noInsights: 'ఇంకా అంతర్దృష్టి లేదు. ట్రాక్ చేస్తూ ఉండండి!' },
  ai: { title: 'AI సహాయకుడు', cryDetector: 'ఏడుపు గుర్తింపు', listening: 'వింటోంది...', analyzing: 'విశ్లేషిస్తోంది...', startListening: 'వినడం ప్రారంభించు', stopListening: 'వినడం ఆపు', cryResult: 'ఏడుపు విశ్లేషణ', hunger: 'ఆకలి', sleep: 'నిద్ర', discomfort: 'అసౌకర్యం', pain: 'నొప్పి', unknown: 'తెలియదు', wasCorrrrect: 'ఇది సరైనదా?', yes: 'అవును, సరైనది!', no: 'కాదు, అది...', chatPlaceholder: 'మీ బిడ్డ గురించి ఏదైనా అడగండి...', suggestedQuestions: ['బిడ్డ ఎందుకు ఏడుస్తోంది?', 'సాధారణ నిద్ర ఎంత?', 'తదుపరి టీకా ఎప్పుడు?', 'ఈ వృద్ధి సాధారణమా?'], digitalTwin: 'డిజిటల్ జంట', twinAccuracy: 'అంచనా ఖచ్చితత్వం', insightsTitle: 'AI అంతర్దృష్టులు' },
  tracker: { title: 'ట్రాకర్', feeding: 'తినిపించడం', sleep: 'నిద్ర', diaper: 'డైపర్', growth: 'వృద్ధి', vaccination: 'టీకా', milestone: 'మైలురాయి', breastfeed: 'తల్లిపాలు', formula: 'ఫార్ముల', solid: 'గట్టి ఆహారం', leftSide: 'ఎడమ', rightSide: 'కుడి', both: 'రెండూ', startFeeding: 'తినిపించడం ప్రారంభించు', stopFeeding: 'తినిపించడం ఆపు', feedDuration: 'వ్యవధి', amount: 'పరిమాణం (మిలీ)', brand: 'బ్రాండ్', foodType: 'ఆహార రకం', startSleep: 'బిడ్డ నిద్రపోయింది', stopSleep: 'బిడ్డ మేల్కొంది', sleepDuration: 'నిద్ర వ్యవధి', sleepQuality: 'నిద్ర నాణ్యత', good: 'మంచి', fair: 'సాధారణ', poor: 'చెడు', wet: 'తడిగా', dirty: 'మురికిగా', mixed: 'మిశ్రమం', logDiaper: 'డైపర్ లాగ్', weight: 'బరువు', height: 'ఎత్తు', headCirc: 'తల చుట్టుకొలత', logGrowth: 'వృద్ధి లాగ్', growthChart: 'వృద్ధి చార్ట్', upcoming: 'రాబోయే', overdue: 'ఆలస్యమైన', administered: 'ఇవ్వబడింది', markDone: 'పూర్తైనట్లు గుర్తించు', vaccineDate: 'టీకా తేదీ', achieved: 'సాధించింది', pending: 'పెండింగ్', markAchieved: 'సాధించినట్లు గుర్తించు', categories: { physical: 'శారీరక', social: 'సామాజిక', language: 'భాష', cognitive: 'అభిజ్ఞా' } },
  journal: { title: 'మెమోరీ జర్నల్', addEntry: 'జ్ఞాపకం జోడించు', photos: 'ఫోటోలు', videos: 'వీడియోలు', notes: 'నోట్లు', tags: 'ట్యాగ్లు', mood: { happy: 'సంతోషం', neutral: 'సాధారణం', tired: 'అలసట', worried: 'ఆందోళన' }, monthlyRecap: 'నెలవారీ సారాంశం', memoryBook: 'మెమోరీ బుక్', noEntries: 'ఇంకా జ్ఞాపకాలు లేవు.' },
  profile: { title: 'ప్రొఫైల్', editProfile: 'ప్రొఫైల్ సవరించు', babies: 'నా పిల్లలు', addBaby: 'బిడ్డను జోడించు', family: 'కుటుంబ భాగస్వామ్యం', inviteFamily: 'కుటుంబ సభ్యుడిని ఆహ్వానించు', subscription: 'సభ్యత్వం', upgradePremium: 'ప్రీమియమ్‌కు అప్‌గ్రేడ్ చేయి', doctorReport: 'డాక్టర్ నివేదిక రూపొందించు', settings: 'సెట్టింగులు', language: 'భాష', notifications: 'నోటిఫికేషన్లు', darkMode: 'డార్క్ మోడ్', privacyPolicy: 'గోప్యతా విధానం', termsOfService: 'సేవా నిబంధనలు', helpSupport: 'సహాయం', logout: 'లాగ్ అవుట్', version: 'వెర్షన్ {{version}}' },
  onboarding: { addBaby: 'మీ బిడ్డను జోడించండి', babyName: 'బిడ్డ పేరు', birthDate: 'పుట్టిన తేదీ', gender: 'లింగం', male: 'అబ్బాయి', female: 'అమ్మాయి', other: 'ఇతర', birthWeight: 'పుట్టిన బరువు (కిలో)', birthHeight: 'పుట్టిన ఎత్తు (సెమీ)', enableNotifications: 'నోటిఫికేషన్లు ప్రారంభించు', notificationsDesc: 'తినిపించడం, నిద్ర మరియు టీకా రిమైండర్లు', enableMicrophone: 'మైక్రోఫోన్ ప్రారంభించు', microphoneDesc: 'AI ఏడుపు గుర్తింపుకు అవసరం', enableCamera: 'కెమెరా ప్రారంభించు', cameraDesc: 'విలువైన క్షణాలను నమోదు చేయి', allSet: 'అన్నీ సిద్ధం!', allSetDesc: 'BabySaathi మీకు మరియు మీ బిడ్డకు సహాయం చేయడానికి సిద్ధంగా ఉంది', allowAccess: 'అనుమతి ఇవ్వు', maybeLayer: 'తర్వాత' },
  errors: { network: 'నెట్‌వర్క్ లోపం.', auth: 'ప్రమాణీకరణ విఫలమైంది.', permission: 'అనుమతి నిరాకరించబడింది.', unknown: 'అనుకోని లోపం సంభవించింది.' },
  subscription: { free: 'ఉచితం', premium: 'ప్రీమియమ్', premiumFamily: 'ప్రీమియమ్ ఫ్యామిలీ', perMonth: '/నెల', perYear: '/సంవత్సరం', upgradeNow: 'ఇప్పుడు అప్‌గ్రేడ్ చేయి', features: { free: ['బేసిక్ ట్రాకింగ్', 'బేసిక్ ఏడుపు గుర్తింపు', '30 రోజుల చరిత్ర'], premium: ['AI అంతర్దృష్టులు', 'అంచనాలు', 'అపరిమిత చరిత్ర', 'డాక్టర్ నివేదికలు', 'కుటుంబ భాగస్వామ్యం'], premiumFamily: ['బహుళ పిల్లలు', 'అపరిమిత సంరక్షకులు', 'అధునాతన AI', 'ప్రాధాన్య మద్దతు'] } },
};
